"""TRACE — assemble REAL citations grounded in the retrieval system.

Post 1's third gate, and the one it says "matters more than most people realise."
A model told to "always cite your sources" will happily fabricate
``[Source: document.pdf, page 12]``. Here, citations are assembled by the
**pipeline**, not the model: we take the chunks the Verify gate confirmed support
the answer (and any inline ``[chunk_id]`` markers, if a prompt variant emits
them), keep only those that were actually retrieved, and look the source up in
our store.

A citation therefore *cannot* point to a nonexistent source — it is grounded in
the retrieval system, not generated by the LLM.
"""

from __future__ import annotations

import re
from collections.abc import Sequence

from .schemas import Citation, Chunk, Verification

# Matches "[...]" with no nested brackets or newlines.
_MARKER_RE = re.compile(r"\[([^\[\]\n]+)\]")
# A bracket may hold several ids separated by comma/semicolon.
_SPLIT_RE = re.compile(r"[;,]\s*")

_SNIPPET_CHARS = 200


def extract_citations(
    answer: str,
    chunks: Sequence[Chunk],
    verification: Verification | None = None,
) -> list[Citation]:
    """Assemble grounded :class:`Citation` objects for the answer.

    Sources come primarily from the Verify gate's per-claim ``supporting_chunk_ids``
    (the chunks it confirmed back each grounded claim); any inline ``[chunk_id]``
    markers in the answer are unioned in too. Only ids present in ``chunks`` (the
    retrieved/kept set) survive — anything that isn't a real retrieved chunk is
    dropped, so a citation can never be fabricated.
    """
    valid: dict[str, Chunk] = {c.chunk_id: c for c in chunks}
    ordered_ids: list[str] = []

    for marker in _MARKER_RE.findall(answer or ""):
        for token in _SPLIT_RE.split(marker):
            cid = token.strip()
            if cid in valid and cid not in ordered_ids:
                ordered_ids.append(cid)

    if verification:
        for claim in verification.claims:
            if claim.grounded:
                for cid in claim.chunk_ids:
                    if cid in valid and cid not in ordered_ids:
                        ordered_ids.append(cid)

    citations: list[Citation] = []
    for cid in ordered_ids:
        chunk = valid[cid]
        snippet = chunk.text if len(chunk.text) <= _SNIPPET_CHARS else chunk.text[:_SNIPPET_CHARS] + " …"
        citations.append(
            Citation(
                chunk_id=cid,
                source=chunk.source,
                header_path=chunk.header_path,
                snippet=snippet,
            )
        )
    return citations
